spring:
  profiles: development
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      
server:
  port: 8081
  
  

spring:
  profiles: integrationTest
  data:
    elasticsearch:
      cluster-nodes: localhost:9400