spring:
  profiles: development
  data:
    mongodb:
      uri:  mongodb://127.0.0.1:27017/searchahouse
      
server:
  port: 7070
      
---

spring:
  profiles: integrationTest
  data:
    mongodb:
      uri:  mongodb://127.0.0.1:27017/searchahouseTest
      
      
